### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by kushal-flipkart** [flipkart-incubator/batchman#78]
```
Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find com.google.gson.annotations.SerializedName.value
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Field.getAnnotation(Field.java:242)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldName(ReflectiveTypeAdapterFactory.java:1076)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:156)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
       at com.google.gson.Gson.getDelegateAdapter(Gson.java:442)
       at com.flipkart.batching.toolbox.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:194)
       at com.google.gson.Gson.getAdapter(Gson.java:360)
       at com.google.gson.Gson.fromJson(Gson.java:813)
       at com.google.gson.Gson.fromJson(Gson.java:779)
       at com.google.gson.Gson.fromJson(Gson.java:728)
       at com.google.gson.Gson.fromJson(Gson.java:700)
       at com.flipkart.batching.persistence.GsonSerializationStrategy.deserializeData(GsonSerializationStrategy.java:180)
       at com.flipkart.batching.persistence.TapePersistenceStrategy.getAllDataFromTapeQueue(TapePersistenceStrategy.java:121)
       at com.flipkart.batching.persistence.TapePersistenceStrategy.syncData(TapePersistenceStrategy.java:1106)
       at com.flipkart.batching.persistence.TagBasedPersistenceStrategy.onInitialized(TagBasedPersistenceStrategy.java:55)
       at com.flipkart.batching.strategy.BaseBatchingStrategy.onInitialized(BaseBatchingStrategy.java:57)
       at com.flipkart.batching.strategy.SizeBatchingStrategy.onInitialized(SizeBatchingStrategy.java:60)
       at com.flipkart.batching.strategy.ComboBatchingStrategy.onInitialized(ComboBatchingStrategy.java:51)
       at com.flipkart.batching.strategy.TagBatchingStrategy.onInitialized(TagBatchingStrategy.java:63)
       at com.flipkart.batching.BatchManager.initialize$175fd481(BatchManager.java:1151)
       at com.flipkart.batching.BatchManager$1.run(BatchManager.java:63)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
 Show all 35 Threads

```

**Comment by kushal-flipkart** [comment]
Have not seen this one for a while. Will reopen if reported.
